# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'member_export.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_member_mod(object):
    def setupUi(self, member_mod):
        member_mod.setObjectName("member_mod")
        member_mod.resize(219, 213)
        self.gridLayout = QtWidgets.QGridLayout(member_mod)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_id = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_id)
        self.label_first_name = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_first_name.setFont(font)
        self.label_first_name.setObjectName("label_first_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_first_name)
        self.label_last_name = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_last_name.setFont(font)
        self.label_last_name.setObjectName("label_last_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_last_name)
        self.label_number = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_number.setFont(font)
        self.label_number.setObjectName("label_number")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_number)
        self.label_waiver = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_waiver.setFont(font)
        self.label_waiver.setObjectName("label_waiver")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_waiver)
        self.label_truck = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_truck.setFont(font)
        self.label_truck.setObjectName("label_truck")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_truck)
        self.edit_first_name = QtWidgets.QLineEdit(member_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_first_name.sizePolicy().hasHeightForWidth())
        self.edit_first_name.setSizePolicy(sizePolicy)
        self.edit_first_name.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_first_name.setMaximumSize(QtCore.QSize(110, 16777215))
        self.edit_first_name.setObjectName("edit_first_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_first_name)
        self.edit_last_name = QtWidgets.QLineEdit(member_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_last_name.sizePolicy().hasHeightForWidth())
        self.edit_last_name.setSizePolicy(sizePolicy)
        self.edit_last_name.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_last_name.setMaximumSize(QtCore.QSize(110, 16777215))
        self.edit_last_name.setObjectName("edit_last_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_last_name)
        self.edit_number = QtWidgets.QLineEdit(member_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_number.sizePolicy().hasHeightForWidth())
        self.edit_number.setSizePolicy(sizePolicy)
        self.edit_number.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_number.setMaximumSize(QtCore.QSize(110, 16777215))
        self.edit_number.setObjectName("edit_number")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_number)
        self.check_waiver = QtWidgets.QCheckBox(member_mod)
        self.check_waiver.setText("")
        self.check_waiver.setObjectName("check_waiver")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.check_waiver)
        self.check_truck = QtWidgets.QCheckBox(member_mod)
        self.check_truck.setText("")
        self.check_truck.setObjectName("check_truck")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.check_truck)
        self.label_trailer = QtWidgets.QLabel(member_mod)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_trailer.setFont(font)
        self.label_trailer.setObjectName("label_trailer")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_trailer)
        self.check_trailer = QtWidgets.QCheckBox(member_mod)
        self.check_trailer.setText("")
        self.check_trailer.setObjectName("check_trailer")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.check_trailer)
        self.edit_id = QtWidgets.QLineEdit(member_mod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_id.sizePolicy().hasHeightForWidth())
        self.edit_id.setSizePolicy(sizePolicy)
        self.edit_id.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_id.setMaximumSize(QtCore.QSize(25, 16777215))
        self.edit_id.setStyleSheet("")
        self.edit_id.setText("")
        self.edit_id.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_id.setObjectName("edit_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_id)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(member_mod)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(member_mod)
        QtCore.QMetaObject.connectSlotsByName(member_mod)
        member_mod.setTabOrder(self.edit_id, self.edit_first_name)
        member_mod.setTabOrder(self.edit_first_name, self.edit_last_name)
        member_mod.setTabOrder(self.edit_last_name, self.edit_number)
        member_mod.setTabOrder(self.edit_number, self.check_waiver)
        member_mod.setTabOrder(self.check_waiver, self.check_truck)
        member_mod.setTabOrder(self.check_truck, self.check_trailer)

    def retranslateUi(self, member_mod):
        _translate = QtCore.QCoreApplication.translate
        member_mod.setWindowTitle(_translate("member_mod", "Dialog"))
        self.label_id.setText(_translate("member_mod", "Member ID"))
        self.label_first_name.setText(_translate("member_mod", "First Name"))
        self.label_last_name.setText(_translate("member_mod", "Last Name"))
        self.label_number.setText(_translate("member_mod", "Call #"))
        self.label_waiver.setText(_translate("member_mod", "Waiver Signed"))
        self.label_truck.setText(_translate("member_mod", "Truck Cert"))
        self.label_trailer.setText(_translate("member_mod", "Trailer Cert"))

