# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\homepage_export.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(647, 716))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tabs.sizePolicy().hasHeightForWidth())
        self.main_tabs.setSizePolicy(sizePolicy)
        self.main_tabs.setMinimumSize(QtCore.QSize(0, 500))
        self.main_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tabs.setDocumentMode(False)
        self.main_tabs.setObjectName("main_tabs")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.gridlayout = QtWidgets.QGridLayout(self.tab_main)
        self.gridlayout.setObjectName("gridlayout")
        self.scroll_fields = QtWidgets.QScrollArea(self.tab_main)
        self.scroll_fields.setWidgetResizable(True)
        self.scroll_fields.setObjectName("scroll_fields")
        self.scroll_fields_contents = QtWidgets.QWidget()
        self.scroll_fields_contents.setGeometry(QtCore.QRect(0, 0, 622, 551))
        self.scroll_fields_contents.setObjectName("scroll_fields_contents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scroll_fields_contents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_general = QtWidgets.QLabel(self.scroll_fields_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_general.sizePolicy().hasHeightForWidth())
        self.label_general.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_general.setFont(font)
        self.label_general.setObjectName("label_general")
        self.gridLayout_3.addWidget(self.label_general, 0, 0, 1, 1)
        self.fr_general_info = QtWidgets.QFrame(self.scroll_fields_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr_general_info.sizePolicy().hasHeightForWidth())
        self.fr_general_info.setSizePolicy(sizePolicy)
        self.fr_general_info.setFrameShape(QtWidgets.QFrame.Box)
        self.fr_general_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_general_info.setLineWidth(1)
        self.fr_general_info.setObjectName("fr_general_info")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_general_info)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.form_left_general = QtWidgets.QFormLayout()
        self.form_left_general.setContentsMargins(-1, 5, -1, -1)
        self.form_left_general.setObjectName("form_left_general")
        self.label_requestor = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_requestor.sizePolicy().hasHeightForWidth())
        self.label_requestor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_requestor.setFont(font)
        self.label_requestor.setObjectName("label_requestor")
        self.form_left_general.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_requestor)
        self.edit_requestor = QtWidgets.QLineEdit(self.fr_general_info)
        self.edit_requestor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_requestor.sizePolicy().hasHeightForWidth())
        self.edit_requestor.setSizePolicy(sizePolicy)
        self.edit_requestor.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_requestor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.edit_requestor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.edit_requestor.setAutoFillBackground(True)
        self.edit_requestor.setStyleSheet("")
        self.edit_requestor.setInputMask("")
        self.edit_requestor.setText("")
        self.edit_requestor.setDragEnabled(False)
        self.edit_requestor.setClearButtonEnabled(True)
        self.edit_requestor.setObjectName("edit_requestor")
        self.form_left_general.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_requestor)
        self.label_lead = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lead.sizePolicy().hasHeightForWidth())
        self.label_lead.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lead.setFont(font)
        self.label_lead.setObjectName("label_lead")
        self.form_left_general.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_lead)
        self.edit_lead = QtWidgets.QLineEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_lead.sizePolicy().hasHeightForWidth())
        self.edit_lead.setSizePolicy(sizePolicy)
        self.edit_lead.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_lead.setClearButtonEnabled(True)
        self.edit_lead.setObjectName("edit_lead")
        self.form_left_general.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_lead)
        self.label_attendee = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_attendee.sizePolicy().hasHeightForWidth())
        self.label_attendee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_attendee.setFont(font)
        self.label_attendee.setObjectName("label_attendee")
        self.form_left_general.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_attendee)
        self.btn_modify_attending = QtWidgets.QPushButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_modify_attending.sizePolicy().hasHeightForWidth())
        self.btn_modify_attending.setSizePolicy(sizePolicy)
        self.btn_modify_attending.setObjectName("btn_modify_attending")
        self.form_left_general.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_modify_attending)
        self.label_session_date = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_session_date.sizePolicy().hasHeightForWidth())
        self.label_session_date.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_session_date.setFont(font)
        self.label_session_date.setObjectName("label_session_date")
        self.form_left_general.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_session_date)
        self.label_session_st = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_session_st.sizePolicy().hasHeightForWidth())
        self.label_session_st.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_session_st.setFont(font)
        self.label_session_st.setObjectName("label_session_st")
        self.form_left_general.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_session_st)
        self.time_start = QtWidgets.QTimeEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start.sizePolicy().hasHeightForWidth())
        self.time_start.setSizePolicy(sizePolicy)
        self.time_start.setMaximumSize(QtCore.QSize(70, 16777215))
        self.time_start.setObjectName("time_start")
        self.form_left_general.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_start)
        self.label_session_et = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_session_et.sizePolicy().hasHeightForWidth())
        self.label_session_et.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_session_et.setFont(font)
        self.label_session_et.setObjectName("label_session_et")
        self.form_left_general.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_session_et)
        self.time_end = QtWidgets.QTimeEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end.sizePolicy().hasHeightForWidth())
        self.time_end.setSizePolicy(sizePolicy)
        self.time_end.setMaximumSize(QtCore.QSize(70, 16777215))
        self.time_end.setTime(QtCore.QTime(1, 0, 0))
        self.time_end.setObjectName("time_end")
        self.form_left_general.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.time_end)
        self.label_testing_type = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_testing_type.sizePolicy().hasHeightForWidth())
        self.label_testing_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_testing_type.setFont(font)
        self.label_testing_type.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_testing_type.setObjectName("label_testing_type")
        self.form_left_general.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_testing_type)
        self.layout_type = QtWidgets.QVBoxLayout()
        self.layout_type.setObjectName("layout_type")
        self.radio_dyno = QtWidgets.QRadioButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_dyno.sizePolicy().hasHeightForWidth())
        self.radio_dyno.setSizePolicy(sizePolicy)
        self.radio_dyno.setObjectName("radio_dyno")
        self.radio_type = QtWidgets.QButtonGroup(MainWindow)
        self.radio_type.setObjectName("radio_type")
        self.radio_type.addButton(self.radio_dyno)
        self.layout_type.addWidget(self.radio_dyno)
        self.radio_track = QtWidgets.QRadioButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_track.sizePolicy().hasHeightForWidth())
        self.radio_track.setSizePolicy(sizePolicy)
        self.radio_track.setObjectName("radio_track")
        self.radio_type.addButton(self.radio_track)
        self.layout_type.addWidget(self.radio_track)
        self.layout_type_other = QtWidgets.QHBoxLayout()
        self.layout_type_other.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_type_other.setObjectName("layout_type_other")
        self.radio_type_other = QtWidgets.QRadioButton(self.fr_general_info)
        self.radio_type_other.setText("")
        self.radio_type_other.setChecked(False)
        self.radio_type_other.setAutoExclusive(True)
        self.radio_type_other.setObjectName("radio_type_other")
        self.radio_type.addButton(self.radio_type_other)
        self.layout_type_other.addWidget(self.radio_type_other)
        self.edit_type_other = QtWidgets.QLineEdit(self.fr_general_info)
        self.edit_type_other.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_type_other.sizePolicy().hasHeightForWidth())
        self.edit_type_other.setSizePolicy(sizePolicy)
        self.edit_type_other.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_type_other.setStyleSheet("")
        self.edit_type_other.setText("")
        self.edit_type_other.setReadOnly(False)
        self.edit_type_other.setClearButtonEnabled(True)
        self.edit_type_other.setObjectName("edit_type_other")
        self.layout_type_other.addWidget(self.edit_type_other)
        self.layout_type.addLayout(self.layout_type_other)
        self.form_left_general.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.layout_type)
        self.label_session_loc = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_session_loc.sizePolicy().hasHeightForWidth())
        self.label_session_loc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_session_loc.setFont(font)
        self.label_session_loc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_session_loc.setObjectName("label_session_loc")
        self.form_left_general.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_session_loc)
        self.layout_loc = QtWidgets.QVBoxLayout()
        self.layout_loc.setObjectName("layout_loc")
        self.radio_loc_cage = QtWidgets.QRadioButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_loc_cage.sizePolicy().hasHeightForWidth())
        self.radio_loc_cage.setSizePolicy(sizePolicy)
        self.radio_loc_cage.setObjectName("radio_loc_cage")
        self.radio_loc = QtWidgets.QButtonGroup(MainWindow)
        self.radio_loc.setObjectName("radio_loc")
        self.radio_loc.addButton(self.radio_loc_cage)
        self.layout_loc.addWidget(self.radio_loc_cage)
        self.radio_loc_loading = QtWidgets.QRadioButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_loc_loading.sizePolicy().hasHeightForWidth())
        self.radio_loc_loading.setSizePolicy(sizePolicy)
        self.radio_loc_loading.setObjectName("radio_loc_loading")
        self.radio_loc.addButton(self.radio_loc_loading)
        self.layout_loc.addWidget(self.radio_loc_loading)
        self.radio_loc_casino = QtWidgets.QRadioButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_loc_casino.sizePolicy().hasHeightForWidth())
        self.radio_loc_casino.setSizePolicy(sizePolicy)
        self.radio_loc_casino.setObjectName("radio_loc_casino")
        self.radio_loc.addButton(self.radio_loc_casino)
        self.layout_loc.addWidget(self.radio_loc_casino)
        self.layout_loc_other = QtWidgets.QHBoxLayout()
        self.layout_loc_other.setObjectName("layout_loc_other")
        self.radio_loc_other = QtWidgets.QRadioButton(self.fr_general_info)
        self.radio_loc_other.setText("")
        self.radio_loc_other.setObjectName("radio_loc_other")
        self.radio_loc.addButton(self.radio_loc_other)
        self.layout_loc_other.addWidget(self.radio_loc_other)
        self.edit_loc_other = QtWidgets.QLineEdit(self.fr_general_info)
        self.edit_loc_other.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_loc_other.sizePolicy().hasHeightForWidth())
        self.edit_loc_other.setSizePolicy(sizePolicy)
        self.edit_loc_other.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_loc_other.setStyleSheet("")
        self.edit_loc_other.setText("")
        self.edit_loc_other.setReadOnly(False)
        self.edit_loc_other.setClearButtonEnabled(True)
        self.edit_loc_other.setObjectName("edit_loc_other")
        self.layout_loc_other.addWidget(self.edit_loc_other)
        self.layout_loc.addLayout(self.layout_loc_other)
        self.form_left_general.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.layout_loc)
        self.date_session = QtWidgets.QDateEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_session.sizePolicy().hasHeightForWidth())
        self.date_session.setSizePolicy(sizePolicy)
        self.date_session.setCalendarPopup(True)
        self.date_session.setDate(QtCore.QDate(2019, 1, 31))
        self.date_session.setObjectName("date_session")
        self.form_left_general.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_session)
        self.horizontalLayout_3.addLayout(self.form_left_general)
        self.form_right_general = QtWidgets.QFormLayout()
        self.form_right_general.setContentsMargins(-1, 5, -1, -1)
        self.form_right_general.setObjectName("form_right_general")
        self.label_part = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_part.sizePolicy().hasHeightForWidth())
        self.label_part.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_part.setFont(font)
        self.label_part.setObjectName("label_part")
        self.form_right_general.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_part)
        self.edit_part = QtWidgets.QLineEdit(self.fr_general_info)
        self.edit_part.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_part.sizePolicy().hasHeightForWidth())
        self.edit_part.setSizePolicy(sizePolicy)
        self.edit_part.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_part.setClearButtonEnabled(True)
        self.edit_part.setObjectName("edit_part")
        self.form_right_general.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_part)
        self.label_cat = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cat.sizePolicy().hasHeightForWidth())
        self.label_cat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cat.setFont(font)
        self.label_cat.setObjectName("label_cat")
        self.form_right_general.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cat)
        self.edit_cat = QtWidgets.QLineEdit(self.fr_general_info)
        self.edit_cat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_cat.sizePolicy().hasHeightForWidth())
        self.edit_cat.setSizePolicy(sizePolicy)
        self.edit_cat.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_cat.setClearButtonEnabled(True)
        self.edit_cat.setObjectName("edit_cat")
        self.form_right_general.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_cat)
        self.label_doc_num = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_doc_num.sizePolicy().hasHeightForWidth())
        self.label_doc_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_doc_num.setFont(font)
        self.label_doc_num.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_doc_num.setObjectName("label_doc_num")
        self.form_right_general.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_doc_num)
        self.layout_doc_num = QtWidgets.QVBoxLayout()
        self.layout_doc_num.setObjectName("layout_doc_num")
        self.edit_doc_num = QtWidgets.QLineEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_doc_num.sizePolicy().hasHeightForWidth())
        self.edit_doc_num.setSizePolicy(sizePolicy)
        self.edit_doc_num.setMaximumSize(QtCore.QSize(135, 16777215))
        self.edit_doc_num.setClearButtonEnabled(True)
        self.edit_doc_num.setObjectName("edit_doc_num")
        self.layout_doc_num.addWidget(self.edit_doc_num)
        self.btn_get_num = QtWidgets.QPushButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_get_num.sizePolicy().hasHeightForWidth())
        self.btn_get_num.setSizePolicy(sizePolicy)
        self.btn_get_num.setObjectName("btn_get_num")
        self.layout_doc_num.addWidget(self.btn_get_num)
        self.form_right_general.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.layout_doc_num)
        self.label_desc = QtWidgets.QLabel(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_desc.sizePolicy().hasHeightForWidth())
        self.label_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_desc.setFont(font)
        self.label_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_desc.setObjectName("label_desc")
        self.form_right_general.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_desc)
        self.edit_desc = QtWidgets.QTextEdit(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_desc.sizePolicy().hasHeightForWidth())
        self.edit_desc.setSizePolicy(sizePolicy)
        self.edit_desc.setMaximumSize(QtCore.QSize(135, 300))
        self.edit_desc.setObjectName("edit_desc")
        self.form_right_general.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_desc)
        self.btn_submit_form = QtWidgets.QPushButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit_form.sizePolicy().hasHeightForWidth())
        self.btn_submit_form.setSizePolicy(sizePolicy)
        self.btn_submit_form.setObjectName("btn_submit_form")
        self.form_right_general.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn_submit_form)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.form_right_general.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.btn_export = QtWidgets.QPushButton(self.fr_general_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setObjectName("btn_export")
        self.form_right_general.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.btn_export)
        self.horizontalLayout_3.addLayout(self.form_right_general)
        self.gridLayout_3.addWidget(self.fr_general_info, 3, 0, 1, 1)
        self.btn_import = QtWidgets.QPushButton(self.scroll_fields_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_3.addWidget(self.btn_import, 2, 0, 1, 1)
        self.scroll_fields.setWidget(self.scroll_fields_contents)
        self.gridlayout.addWidget(self.scroll_fields, 3, 0, 1, 1)
        self.layout_document_settings = QtWidgets.QFormLayout()
        self.layout_document_settings.setObjectName("layout_document_settings")
        self.btn_open_template = QtWidgets.QPushButton(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_template.sizePolicy().hasHeightForWidth())
        self.btn_open_template.setSizePolicy(sizePolicy)
        self.btn_open_template.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_open_template.setObjectName("btn_open_template")
        self.layout_document_settings.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_open_template)
        self.file_path = QtWidgets.QLabel(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_path.sizePolicy().hasHeightForWidth())
        self.file_path.setSizePolicy(sizePolicy)
        self.file_path.setObjectName("file_path")
        self.layout_document_settings.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.file_path)
        self.btn_save_doc = QtWidgets.QPushButton(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_doc.sizePolicy().hasHeightForWidth())
        self.btn_save_doc.setSizePolicy(sizePolicy)
        self.btn_save_doc.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_save_doc.setMaximumSize(QtCore.QSize(110, 16777215))
        self.btn_save_doc.setObjectName("btn_save_doc")
        self.layout_document_settings.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_save_doc)
        self.label_save_doc = QtWidgets.QLabel(self.tab_main)
        self.label_save_doc.setEnabled(True)
        self.label_save_doc.setObjectName("label_save_doc")
        self.layout_document_settings.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_save_doc)
        self.gridlayout.addLayout(self.layout_document_settings, 1, 0, 1, 1)
        self.main_tabs.addTab(self.tab_main, "")
        self.tab_roster = QtWidgets.QWidget()
        self.tab_roster.setObjectName("tab_roster")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_roster)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.btn_open_roster = QtWidgets.QPushButton(self.tab_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_roster.sizePolicy().hasHeightForWidth())
        self.btn_open_roster.setSizePolicy(sizePolicy)
        self.btn_open_roster.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_open_roster.setObjectName("btn_open_roster")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_open_roster)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_close_roster = QtWidgets.QPushButton(self.tab_roster)
        self.btn_close_roster.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_roster.sizePolicy().hasHeightForWidth())
        self.btn_close_roster.setSizePolicy(sizePolicy)
        self.btn_close_roster.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_close_roster.setObjectName("btn_close_roster")
        self.horizontalLayout_4.addWidget(self.btn_close_roster)
        self.btn_save_roster = QtWidgets.QPushButton(self.tab_roster)
        self.btn_save_roster.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_roster.sizePolicy().hasHeightForWidth())
        self.btn_save_roster.setSizePolicy(sizePolicy)
        self.btn_save_roster.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_save_roster.setObjectName("btn_save_roster")
        self.horizontalLayout_4.addWidget(self.btn_save_roster)
        self.label_roster = QtWidgets.QLabel(self.tab_roster)
        self.label_roster.setObjectName("label_roster")
        self.horizontalLayout_4.addWidget(self.label_roster)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.btn_create_roster = QtWidgets.QPushButton(self.tab_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_roster.sizePolicy().hasHeightForWidth())
        self.btn_create_roster.setSizePolicy(sizePolicy)
        self.btn_create_roster.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_create_roster.setObjectName("btn_create_roster")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_create_roster)
        self.label_create_roster = QtWidgets.QLabel(self.tab_roster)
        self.label_create_roster.setObjectName("label_create_roster")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_create_roster)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tree_roster = QtWidgets.QTreeWidget(self.tab_roster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_roster.sizePolicy().hasHeightForWidth())
        self.tree_roster.setSizePolicy(sizePolicy)
        self.tree_roster.setMinimumSize(QtCore.QSize(0, 0))
        self.tree_roster.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tree_roster.setObjectName("tree_roster")
        self.gridLayout_2.addWidget(self.tree_roster, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.tab_roster)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_roster)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_roster)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.main_tabs.addTab(self.tab_roster, "")
        self.gridLayout.addWidget(self.main_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_Template_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_Template_File.setObjectName("actionOpen_Template_File")
        self.actionSave_Testing_Doc = QtWidgets.QAction(MainWindow)
        self.actionSave_Testing_Doc.setObjectName("actionSave_Testing_Doc")
        self.menuFile.addAction(self.actionOpen_Template_File)
        self.menuFile.addAction(self.actionSave_Testing_Doc)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Testing Doc Maker"))
        self.label_general.setText(_translate("MainWindow", "General Info"))
        self.label_requestor.setText(_translate("MainWindow", "Name of requestor:"))
        self.label_lead.setText(_translate("MainWindow", "Test Lead:"))
        self.label_attendee.setText(_translate("MainWindow", "Attendee List:"))
        self.btn_modify_attending.setText(_translate("MainWindow", "Modify List"))
        self.label_session_date.setText(_translate("MainWindow", "Test Session Date:"))
        self.label_session_st.setText(_translate("MainWindow", "Start Time:"))
        self.label_session_et.setText(_translate("MainWindow", "End Time:"))
        self.label_testing_type.setText(_translate("MainWindow", "Testing Type:"))
        self.radio_dyno.setText(_translate("MainWindow", "Dyno"))
        self.radio_track.setText(_translate("MainWindow", "Track"))
        self.edit_type_other.setPlaceholderText(_translate("MainWindow", "Other"))
        self.label_session_loc.setText(_translate("MainWindow", "Testing Location:"))
        self.radio_loc_cage.setText(_translate("MainWindow", "Cage"))
        self.radio_loc_loading.setText(_translate("MainWindow", "Loading Dock"))
        self.radio_loc_casino.setText(_translate("MainWindow", "Casino"))
        self.edit_loc_other.setPlaceholderText(_translate("MainWindow", "Other"))
        self.date_session.setDisplayFormat(_translate("MainWindow", "yyyy-dd-MM"))
        self.label_part.setText(_translate("MainWindow", "Part Being Tested:"))
        self.edit_part.setPlaceholderText(_translate("MainWindow", "CFR19"))
        self.label_cat.setText(_translate("MainWindow", "Testing Category"))
        self.edit_cat.setPlaceholderText(_translate("MainWindow", "Testing"))
        self.label_doc_num.setText(_translate("MainWindow", "Testing Doc Number:"))
        self.edit_doc_num.setPlaceholderText(_translate("MainWindow", "10997"))
        self.btn_get_num.setText(_translate("MainWindow", "Autofill Number"))
        self.label_desc.setText(_translate("MainWindow", "Description:"))
        self.edit_desc.setPlaceholderText(_translate("MainWindow", "Testing"))
        self.btn_submit_form.setText(_translate("MainWindow", "Submit Form"))
        self.btn_export.setText(_translate("MainWindow", "Export As Template"))
        self.btn_import.setText(_translate("MainWindow", "Import Template"))
        self.btn_open_template.setText(_translate("MainWindow", "Choose Template File"))
        self.file_path.setText(_translate("MainWindow", "No document chosen."))
        self.btn_save_doc.setText(_translate("MainWindow", "Save Testing Doc"))
        self.label_save_doc.setText(_translate("MainWindow", "Document not saved."))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_main), _translate("MainWindow", "Main Page"))
        self.btn_open_roster.setText(_translate("MainWindow", "Choose Roster File"))
        self.btn_close_roster.setText(_translate("MainWindow", "Close Roster File"))
        self.btn_save_roster.setText(_translate("MainWindow", "Save Roster File"))
        self.label_roster.setText(_translate("MainWindow", "No roster file chosen."))
        self.btn_create_roster.setText(_translate("MainWindow", "Create Roster File"))
        self.label_create_roster.setText(_translate("MainWindow", "Roster File not created."))
        self.tree_roster.setSortingEnabled(True)
        self.tree_roster.headerItem().setText(0, _translate("MainWindow", "First Name"))
        self.tree_roster.headerItem().setText(1, _translate("MainWindow", "Last Name"))
        self.tree_roster.headerItem().setText(2, _translate("MainWindow", "Cell Phone Number"))
        self.tree_roster.headerItem().setText(3, _translate("MainWindow", "Waiver Signed"))
        self.tree_roster.headerItem().setText(4, _translate("MainWindow", "Truck Cert"))
        self.tree_roster.headerItem().setText(5, _translate("MainWindow", "Trailer Cert"))
        self.pushButton.setText(_translate("MainWindow", "Add Member"))
        self.pushButton_2.setText(_translate("MainWindow", "Modify Member"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove Member(s)"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_roster), _translate("MainWindow", "Roster Management"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Template_File.setText(_translate("MainWindow", "Open Template File"))
        self.actionOpen_Template_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Testing_Doc.setText(_translate("MainWindow", "Save Testing Doc"))
        self.actionSave_Testing_Doc.setShortcut(_translate("MainWindow", "Ctrl+S"))

